// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { makeGuardedFetch } from '@/lib/auth-retry';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// ── Token caducado = cero filas, sin error visible ───────────────────────────────────────────
// Con RLS, una petición con un token inválido no falla "a la vista": PostgREST contesta 401 y la
// pantalla pinta una lista vacía ("no hay campañas") aunque los datos estén ahí. Aquí se
// intercepta: se renueva el token UNA vez (una sola renovación para todas las peticiones en
// vuelo) y se repite la petición. Si la renovación tampoco sale, se avisa a la interfaz para que
// lo diga y ofrezca volver a entrar — nunca se cierra la sesión por sorpresa.
let clientRef: SupabaseClient<Database> | null = null;

const guardedFetch = makeGuardedFetch({
  fetchImpl: (input: any, init?: RequestInit) => fetch(input, init),
  refresh: async () => {
    try {
      const { data, error } = await clientRef!.auth.refreshSession();
      return error ? null : (data.session?.access_token ?? null);
    } catch {
      return null;
    }
  },
});

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: { fetch: guardedFetch },
});

clientRef = supabase;
